sudo: required
services:
  - docker

before_install:
  - docker build -t ryanzzff/docker-multi-containers-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ryanzzff/docker-multi-containers-react-test npm run test

after_success:
  - docker build -t ryanzzff/docker-multi-containers-client ./client
  - docker build -t ryanzzff/docker-multi-containers-nginx ./nginx
  - docker build -t ryanzzff/docker-multi-containers-server ./server
  - docker build -t ryanzzff/docker-multi-containers-worker ./worker

  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push to docker hub
  - docker push ryanzzff/docker-multi-containers-client
  - docker push ryanzzff/docker-multi-containers-nginx
  - docker push ryanzzff/docker-multi-containers-server
  - docker push ryanzzff/docker-multi-containers-worker

deploy:
  provider: elasticbeanstalk
  region: ap-east-1
  app: docker-multi-containers
  env: DockerMultiContainers-env
  bucket_name: elasticbeanstalk-ap-east-1-623712114373
  bucket_path: docker-multi-containers # equal to app name
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  on:
    branch: master


